version: 2.1

orbs:
  codecov: codecov/codecov@3.1.1

jobs:
  build:
    parameters:
      version:
        type: string
    docker:
      - image: cimg/python:<< parameters.version >>
    steps:
      - checkout
      - restore_cache:
          key: v1-<< parameters.version >>-min-dependency-cache-{{ checksum "dev-requirements.txt" }}
      - run:
          name: install python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r dev-requirements.txt
      - save_cache:
          key: v1-<< parameters.version >>-min-dependency-cache-{{ checksum "dev-requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: test if package installs
          command: |
            . venv/bin/activate
            python3 setup.py install
  test-module:
    parameters:
      module:
        type: string
      benchmarks:
        type: string
      experiments:
        type: string
      tutorials:
        type: string
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - restore_cache:
          key: v1-3.8-dependency-cache-{{ checksum "dev-requirements.txt" }}
      - run:
          name: install python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r dev-requirements.txt
            pip install -e .
      - save_cache:
          key: v1-3.8-dependency-cache-{{ checksum "dev-requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: run code linting
          command: |
            . venv/bin/activate
            black --check --diff ./<< parameters.module >>
            black --check --diff ./<< parameters.benchmarks >>
            black --check --diff ./<< parameters.experiments >>
            black --check --diff ./<< parameters.tutorials >>
      - run:
          name: run tests and coverage
          command: |
            . venv/bin/activate
            pytest --junitxml=test-reports/junit.xml --cov-report=xml --cov=./<< parameters.module >> ./<< parameters.module >>
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
      - codecov/upload:
          file: "coverage.xml"
  deploy:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - restore_cache:
          key: v1-3.8-dependency-cache-{{ checksum "dev-requirements.txt" }}
      - run:
          name: install python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r dev-requirements.txt
            pip install -e .
      - save_cache:
          key: v1-3.8-dependency-cache-{{ checksum "dev-requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: verify git tag vs. version
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python setup.py verify
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = __token__" >> ~/.pypirc
            echo -e "password = $PIP_TOKEN" >> ~/.pypirc
      - run:
          name: create packages
          command: |
            python setup.py sdist bdist_wheel
      - run:
          name: upload to pypi
          command: |
            . venv/bin/activate
            twine upload dist/*
workflows:
  build-test-deploy:
    jobs:
      - build:
          name: "v3.6"
          version: "3.6"
      - build:
          name: "v3.7"
          version: "3.7"
      - build:
          name: "v3.8"
          version: "3.8"
      - test-module:
          name: "proglearn"
          module: "proglearn"
          benchmarks: "benchmarks/"
          experiments: "docs/experiments/"
          tutorials: "docs/tutorials/"
          requires:
            - "v3.8"
      - deploy:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
