import numpy as np
import seaborn as sns

def get_colors(colors, inds):
    """
    Parameters
    ---
    colors : RGB tuples
        Contains RGB tuples as generated by seaborn
    inds : int array
        The input array with class labels
    """
    c = [colors[i] for i in inds]
    return c


def plot_gaussians(X, y): 
    """
    Plot the gaussians with the color according to the class label 

    Parameters
    ---
    X : 2D array 
        A multi-dimensional array which contains the coordinates of points in the multivariate random distribution 
    Y : int array
        Contains the class labels for each data point in X
    """
    colors = sns.color_palette("Dark2", n_colors=2)
    fig, ax = plt.subplots(1, 1, figsize=(8, 8))
    ax.scatter(X[:, 0], X[:, 1], c=get_colors(colors, y), s=50)
    ax.set_title("Created Gaussians", fontsize=30)
    plt.tight_layout()
    
